// Generated from Lista de Retos y Preguntas.txt.
// Potentially unsafe/non-consensual challenges are intentionally excluded.
const importedAdultContent = <String, Map<String, List<String>>>{
  'pareja_atrevido': {
    'verdad': [
      '¿Cuál es la fantasía sexual que más te excita de mí?',
      '¿Qué parte de mi cuerpo te pone más cachondo?',
      '¿Alguna vez te has masturbado pensando en mí en el trabajo?',
      '¿Qué posición te vuelve loco/a?',
      '¿Te gusta que te digan cosas sucias durante el sexo?',
      '¿Cuál es el lugar más atrevido donde has querido follar conmigo?',
      '¿Prefieres que te domine o que te deje dominar?',
      '¿Qué ropa interior mía te pone más de los nervios?',
      '¿Has fantaseado con que alguien nos vea?',
      '¿Qué es lo más sucio que te gustaría que te hiciera con la boca?',
      '¿Te excita el riesgo de que nos descubran?',
      '¿Cuál es tu zona erógena favorita que casi nadie toca?',
      '¿Has usado juguetes sexuales pensando en mí?',
      '¿Qué te gustaría que te chupara más tiempo?',
      '¿Te gusta el sexo oral más dando o recibiendo?',
      '¿Alguna vez has grabado un vídeo íntimo de nosotros?',
      '¿Qué nombre sucio te gusta que te diga en la cama?',
      '¿Te pone caliente que te marque o te muerda?',
      '¿Cuál es la vez que más te has corrido conmigo?',
      '¿Te gusta el sexo matutino o nocturno más intenso?',
      '¿Has fantaseado con hacer un trío conmigo?',
      '¿Qué parte de mi cuerpo te gustaría lamer más despacio?',
      '¿Te excita el sexo con ropa (semi-vestidos)?',
      '¿Cuál es tu fetiche más suave que aún no hemos probado?',
      '¿Te gusta que te agarre del pelo?',
      '¿Has mirado porno de parejas y pensado en nosotros?',
      '¿Qué es lo más atrevido que te gustaría hacer en el coche?',
      '¿Te pone vergonzoso o excitante hablar de sexo en público?',
      '¿Cuál es el cumplido sexual más directo que te han hecho?',
      '¿Prefieres que te folle lento y profundo o rápido y duro?',
      '¿Te gusta el roleplay suave?',
      '¿Qué te gustaría que te hiciera mientras estás trabajando desde casa?',
      '¿Has tenido un orgasmo solo de estimulación oral?',
      '¿Te excita el olor de mi cuerpo después de follar?',
      '¿Cuál es tu posición favorita para hacer el 69?',
      '¿Te gusta que te diga lo que siento mientras te penetro/a?',
      '¿Has usado comida de forma sexual?',
      '¿Qué es lo más íntimo que te gustaría compartir conmigo en la cama?',
      '¿Te pone caliente el sexo después de una discusión?',
      '¿Cuál es tu fantasía de “primera vez” conmigo si empezáramos de cero?',
      '¿Te gusta que te toque en lugares públicos de forma discreta?',
      '¿Has fantaseado con follar en la ducha juntos de forma más intensa?',
      '¿Qué juguete sexual te gustaría introducir ya?',
      '¿Cuál es el mejor orgasmo que has tenido conmigo y por qué?',
      '¿Te gusta que te deje marcas de besos o chupetones?',
      '¿Has pensado en hacer un vídeo solo para nosotros?',
      '¿Qué te gustaría que te susurrara al oído mientras te penetro/a?',
      '¿Prefieres el sexo con luz o en completa oscuridad?',
      '¿Cuál es la cosa más atrevida que harías por mí esta misma noche?',
    ],
    'reto': [
      'Quítate una prenda y déjala en el suelo ahora mismo.',
      'Dame un beso de 30 segundos con lengua en el cuello.',
      'Susúrrame al oído la fantasía más sucia que tengas de mí.',
      'Quítame la ropa interior con los dientes (o inténtalo).',
      'Hazme un masaje de 1 minuto solo en la zona íntima (por encima de la ropa).',
      'Dime tres cosas sucias que quieres que te haga esta noche.',
      'Bésame como si fuera la última vez, 20 segundos.',
      'Enséñame tu parte favorita de tu cuerpo y explícame por qué.',
      'Hazme un baile sexy de 30 segundos.',
      'Chúpame un dedo como si fuera otra cosa.',
      'Ponte de rodillas y bésame el estómago.',
      'Cuéntame en voz alta cómo te gustaría que te follara ahora.',
      'Quítate la camiseta y deja que te mire 20 segundos sin tocar.',
      'Hazme cosquillas eróticas en el cuello y orejas.',
      'Dime el nombre más sucio que quieres que te llame.',
      'Lame mi cuello durante 15 segundos.',
      'Enséñame cómo te masturbas (sin llegar al final).',
      'Ponte encima de mí y muévete como si estuvieras montando.',
      'Dame un oral suave de 20 segundos (por encima o debajo según comodidad).',
      'Escribe con el dedo en mi espalda algo sucio.',
      'Quítame un calcetín o prenda con la boca.',
      'Susurra “fóllame” al oído de forma realista.',
      'Hazme un striptease de 40 segundos.',
      'Bésame todo el torso durante 30 segundos.',
      'Dime qué te gustaría que te hiciera con la lengua ahora mismo.',
      'Ponte en posición de 69 (solo posar).',
      'Chúpame el lóbulo de la oreja mientras me agarras la cintura.',
      'Enséñame tu expresión cuando estás a punto de correrte.',
      'Hazme un masaje de pechos/pecho de 1 minuto.',
      'Cuéntame tu mejor recuerdo sexual conmigo mientras me tocas.',
      'Quítate el sujetador/pantalón y quédate así 30 segundos.',
      'Dame un beso en el interior del muslo.',
      'Di en voz alta lo que sientes cuando te penetro/a.',
      'Hazme el movimiento de cadera más sexy que sepas.',
      'Lame mi clavícula y cuello.',
      'Ponte de espaldas y deja que te mire el culo 20 segundos.',
      'Susurra tu fantasía más atrevida mientras me acaricias.',
      'Hazme un oral corto e intenso (20 segundos).',
      'Enséñame cómo quieres que te toque ahora.',
      'Bésame el ombligo y baja un poco más.',
      'Dime tres posiciones que quieres probar esta semana.',
      'Quítame la ropa de la parte superior con lentitud.',
      'Hazme cosquillas eróticas en la espalda baja.',
      'Ponte en cuatro y mira hacia atrás de forma provocadora.',
      'Cuéntame qué te pone más cuando me ves desnudo/a.',
      'Dame un abrazo por detrás y susurra algo sucio.',
      'Chúpame los dedos uno por uno.',
      'Hazme un baile en el regazo de 30 segundos.',
      'Enséñame tu mejor cara de placer.',
      'Termina con un beso muy profundo y di “esta noche te follo como quieras”.',
    ],
  },
  'pareja_extremo': {
    'verdad': [
      '¿Cuál es la fantasía más oscura o extrema que has tenido conmigo?',
      '¿Has fantaseado con que te use como objeto sexual toda la noche?',
      '¿Qué es lo más degradante (de forma consensuada) que te gustaría que te diga?',
      '¿Te pone el dolor controlado (mordiscos, azotes suaves/fuertes)?',
      '¿Has pensado en un trío o más personas conmigo?',
      '¿Cuál es el límite que nunca has cruzado pero te tienta?',
      '¿Te excita el control total (bondage ligero o verbal)?',
      '¿Has fantaseado con follar en un lugar donde podríamos ser descubiertos fácilmente?',
      '¿Qué juguete extremo te gustaría probar ya?',
      '¿Te gusta la idea de que te deje marcas visibles?',
      '¿Has tenido pensamientos de dominación extrema conmigo?',
      '¿Cuál es tu mayor fetiche prohibido?',
      '¿Has fantaseado con intercambiar parejas?',
      '¿Qué es lo más sucio que te gustaría que te hiciera en la boca?',
      '¿Cuál es la fantasía de poder que más te calienta?',
      '¿Te gusta que te traten como un juguete sexual?',
      '¿Has fantaseado con sexo en grupo o orgías?',
      '¿Qué parte de mi cuerpo te gustaría usar de forma más extrema?',
      '¿Te excita el riesgo de ser descubiertos por vecinos o familia?',
      '¿Has tenido un orgasmo solo de humillación verbal?',
      '¿Cuál es el acto más extremo que harías por mí esta noche?',
      '¿Te pone el sexo después de una pelea fuerte?',
      '¿Has fantaseado con que te folle en público de forma casi visible?',
      '¿Te excita el control de orgasmos (negarte el final)?',
      '¿Has pensado en usar comida o líquidos de forma extrema?',
      '¿Cuál es tu fantasía de “usar y tirar” más intensa?',
      '¿Te gusta la idea de que te grabe mientras te uso?',
      '¿Has fantaseado con roles de amo/esclavo?',
      '¿Qué es lo más asqueroso (de forma sexual) que te gusta?',
      '¿Te pone el sexo con dolor intenso controlado?',
      '¿Has pensado en invitar a alguien a mirarnos?',
      '¿Cuál es el límite de degradación que aceptarías?',
      '¿Qué te gustaría que te hiciera con un juguete grande o intenso?',
      '¿Te pone que te trate como un puta/puto solo mío/a?',
      '¿Has fantaseado con follar en el baño de un bar o local?',
      '¿Cuál es la cosa más extrema que has visto en porno y quieres probar?',
      '¿Te gusta la idea de que te deje sin ropa en casa todo el día?',
      '¿Has pensado en un casting o situación de “prueba”?',
      '¿Qué es lo más extremo que te gustaría que te diga mientras te penetro/a?',
      '¿Te excita el sexo con múltiples orgasmos forzados?',
      '¿Has fantaseado con que te use delante de un espejo o cámara?',
      '¿Cuál es tu fantasía de sumisión total más profunda?',
      '¿Qué harías si te diera permiso total para hacer lo que quisieras conmigo esta noche?',
    ],
    'reto': [
      'Quítate toda la ropa y quédate desnudo/a 1 minuto mientras te miro.',
      'Ponte de rodillas y pídeme que te use como quiera.',
      'Dime las palabras más degradantes que quieres que te diga ahora.',
      'Déjame azotarte (suave o fuerte según acuerdo) 10 veces.',
      'Ponte en posición de sumisión (como quieras) y no te muevas.',
      'Cuéntame tu fantasía más extrema en voz alta y detallada.',
      'Déjame atarte las manos (con lo que haya) 1 minuto.',
      'Chúpame o lámelo todo lo que quiera durante 30 segundos.',
      'Di en voz alta “soy tu puta/puto” o la frase que elijas.',
      'Déjame marcar tu cuello o muslo con un chupetón fuerte.',
      'Susurra cómo quieres que te folle de la forma más dura.',
      'Enséñame cómo te masturbas de la forma más extrema.',
      'Pídeme que te folle como un objeto.',
      'Déjame escribir algo sucio en tu cuerpo con un rotulador.',
      'Haz el movimiento más obsceno que sepas en el regazo.',
      'Déjame usarte la boca mientras te agarro del pelo.',
      'Di tu límite más bajo y pídeme que lo cruce un poco.',
      'Ponte en posición de 69 extremo y manténla.',
      'Déjame azotarte el culo mientras me dices lo que sientes.',
      'Quítate la ropa y camina desnudo/a por la habitación.',
      'Di “fóllame más duro” de forma realista y repetida.',
      'Ponte de rodillas y abre la boca.',
      'Lame o chupa lo que te indique durante 30 segundos.',
      'Di la frase más sucia y extrema que se te ocurra.',
      'Déjame usarte contra la pared o el suelo.',
      'Enséñame tu expresión más sumisa.',
      'Pídeme que te trate como un juguete sexual.',
      'Déjame dejar marcas visibles (con consentimiento).',
      'Haz un oral tan profundo como puedas.',
      'Cuéntame cómo quieres que te degrade verbalmente.',
      'Ponte en la posición más vulnerable y mantente quieto/a.',
      'Di “haz lo que quieras conmigo” y cúmplelo 1 minuto.',
      'Déjame controlar tu cuerpo completamente 30 segundos.',
      'Enséñame cómo te corres de la forma más intensa.',
      'Pídeme que te folle sin piedad.',
      'Déjame escribir o marcar algo extremo en ti.',
      'Haz el sonido más obsceno que puedas.',
      'Di tu fantasía más prohibida mientras te toco.',
      'Ponte completamente a mi disposición 1 minuto.',
      'Termina pidiendo que te folle de la forma más extrema que se te ocurra.',
    ],
  },
  'fiesta_atrevido': {
    'verdad': [
      '¿Cuál es la cosa más atrevida que has hecho en una fiesta?',
      '¿Has follado o casi follado en un baño de fiesta?',
      '¿Quién de los presentes te parece más atractivo/a sexualmente?',
      '¿Has tenido un beso de tres o más en una fiesta?',
      '¿Cuál es tu mayor conquista en una noche de fiesta?',
      '¿Has enviado nudes estando borracho/a en una fiesta?',
      '¿Te has masturbado en un baño de fiesta?',
      '¿Cuál es el lugar más público donde has tenido contacto sexual?',
      '¿Has hecho un striptease o algo similar en una fiesta?',
      '¿Quién de aquí te gustaría besar ahora mismo?',
      '¿Has tenido sexo con alguien que conociste esa misma noche?',
      '¿Cuál es tu mejor historia de “casi nos pillan”?',
      '¿Has bebido de forma sexual (chupitos del cuerpo)?',
      '¿Te has quitado ropa en una fiesta por un reto?',
      '¿Quién de los presentes tiene el mejor cuerpo según tú?',
      '¿Has fantaseado con alguien de esta fiesta?',
      '¿Cuál es la cosa más sucia que has dicho estando borracho/a?',
      '¿Has tenido un orgasmo en una fiesta (solo o acompañado)?',
      '¿Te gusta el juego de verdad o reto cuando se pone sexual?',
      '¿Has besado a alguien del mismo sexo en una fiesta?',
      '¿Cuál es tu recuerdo más caliente de una fiesta?',
      '¿Quién de aquí te pondría más nervioso/a si te retara?',
      '¿Has hecho el 69 o algo similar en una fiesta?',
      '¿Cuál es la posición más atrevida que has hecho fuera de casa?',
      '¿Has grabado algo sexual en una fiesta?',
      '¿Te has desnudado parcialmente por un reto de grupo?',
      '¿Quién de los presentes te gustaría que te diera un masaje ahora?',
      '¿Has tenido un trío o situación de tres en ambiente de fiesta?',
      '¿Cuál es tu mayor arrepentimiento sexual de una fiesta?',
      '¿Has usado juguetes o algo improvisado en una fiesta?',
      '¿Te gusta cuando el juego se pone físico y sexual?',
      '¿Quién de aquí tiene la sonrisa más seductora?',
      '¿Has hecho un baile erótico en una fiesta?',
      '¿Cuál es la cosa más atrevida que harías ahora mismo por 50 euros?',
      '¿Has tenido sexo en el coche después de una fiesta?',
      '¿Quién de los presentes te parece más dominante en la cama?',
      '¿Has chupado o lamedido algo del cuerpo de alguien en una fiesta?',
      '¿Cuál es tu mejor técnica para ligar en fiestas?',
      '¿Has tenido un orgasmo colectivo o casi en grupo?',
      '¿Te has quedado en ropa interior por un reto?',
      '¿Quién de aquí te gustaría que te susurrara algo sucio?',
      '¿Has hecho un reto sexual en una fiesta anterior?',
      '¿Cuál es la persona más inesperada con la que has tenido química sexual en una fiesta?',
      '¿Has bebido alcohol del cuerpo de alguien?',
      '¿Te pone el riesgo de que otros vean lo que haces?',
      '¿Quién de los presentes tiene el mejor culo según tú?',
      '¿Has tenido un beso apasionado con alguien que no conocías de nada?',
      '¿Cuál es la cosa más atrevida que has visto en una fiesta?',
      '¿Harías un reto sexual ahora mismo si te tocara?',
    ],
    'reto': [
      'Elige a alguien y dale un beso de 10 segundos en la boca.',
      'Quítate una prenda y no te la pongas hasta el siguiente turno.',
      'Haz un baile sexy de 20 segundos para el grupo.',
      'Susurra algo sucio al oído de la persona que elijas.',
      'Deja que alguien te dé un chupetón en el cuello.',
      'Ponte de rodillas delante de alguien y dile algo provocador.',
      'Elige a dos personas y haz que se den un beso.',
      'Quítate la camiseta/blusa durante 30 segundos.',
      'Dame (o a quien elijas) un masaje en los muslos de 20 segundos.',
      'Di en voz alta tu fantasía más atrevida de esta noche.',
      'Deja que alguien te quite una prenda con los dientes.',
      'Haz el movimiento de cadera más sexy que sepas.',
      'Elige a alguien y lame su cuello 10 segundos.',
      'Ponte en el regazo de alguien 20 segundos.',
      'Cuenta tu mejor historia sexual de fiesta en detalle.',
      'Deja que el grupo vote quién te parece más atractivo/a.',
      'Haz un striptease de 30 segundos (hasta donde te atrevas).',
      'Bésale el hombro o clavícula a alguien.',
      'Di “quiero follar con…” y completa con alguien del grupo (en broma o no).',
      'Deja que alguien te escriba algo sucio en el brazo.',
      'Haz un oral improvisado a una botella o dedo de forma provocadora.',
      'Elige a alguien y dale un abrazo por detrás muy pegado.',
      'Quítate los pantalones/falda y quédate en ropa interior 20 segundos.',
      'Susurra al oído de tres personas algo diferente y sucio.',
      'Deja que alguien te toque la cintura o cadera 15 segundos.',
      'Haz la cara más sexy de orgasmo que puedas.',
      'Elige a alguien y dile cómo te lo follarías.',
      'Ponte a cuatro patas 10 segundos.',
      'Deja que el grupo te dé un apodo sexual.',
      'Haz un baile en el regazo de alguien.',
      'Chúpale el dedo a alguien de forma erótica.',
      'Di en voz alta la parte del cuerpo que más te gusta de cada uno.',
      'Deja que alguien te quite el sujetador/cinturón (si aplica).',
      'Haz 20 segundos de contacto visual intenso con alguien.',
      'Cuenta qué harías si te dejaran solo/a con la persona que elijas.',
      'Ponte la camiseta de alguien del grupo.',
      'Dale un beso en la mano y súbelo al brazo.',
      'Deja que te hagan un masaje de espalda de 30 segundos.',
      'Di tu posición sexual favorita en voz alta.',
      'Elige a alguien y hazle cosquillas eróticas.',
      'Quítate una prenda interior y enséñala (sin enseñar más).',
      'Haz el sonido más obsceno que puedas.',
      'Deja que alguien te susurre lo que quiere hacerte.',
      'Ponte de pie y deja que te miren 15 segundos como quieran.',
      'Elige a dos personas y haz que te den un beso cada una.',
      'Di “esta noche me atrevo a…” y completa.',
      'Deja que te escriban algo en la piel con un rotulador.',
      'Haz un movimiento de striptease sentado/a.',
      'Elige a alguien y dile “te follo si ganas el próximo reto”.',
      'Termina el turno con un beso al aire muy provocador o real.',
    ],
  },
  'fiesta_extremo': {
    'verdad': [
      '¿Cuál es la cosa más extrema que has hecho en una fiesta?',
      '¿Has tenido sexo completo en un baño o habitación de fiesta?',
      '¿Has participado en un trío o más en ambiente de fiesta?',
      '¿Quién de los presentes te gustaría follar esta misma noche?',
      '¿Cuál es el acto más sucio o degradante que has hecho borracho/a?',
      '¿Has tenido sexo con más de una persona la misma noche?',
      '¿Te has corrido en público o casi en una fiesta?',
      '¿Has usado juguetes o dedos de forma extrema en grupo?',
      '¿Quién de aquí te parece que sería mejor en la cama?',
      '¿Has hecho un casting o situación de “prueba” sexual en fiesta?',
      '¿Cuál es tu mayor historia de sexo en grupo o casi?',
      '¿Has bebido fluidos corporales o hecho algo muy extremo?',
      '¿Te has quedado completamente desnudo/a en una fiesta?',
      '¿Quién de los presentes te gustaría que te dominara?',
      '¿Has hecho bondage o algo de sumisión en una fiesta?',
      '¿Cuál es tu fantasía más extrema que has cumplido en una noche de fiesta?',
      '¿Has tenido un orgasmo forzado o múltiple en grupo?',
      '¿Te has dejado usar por varias personas en una noche?',
      '¿Has hecho sexo anal o extremo en una fiesta?',
      '¿Quién de aquí te pondría más si te retara a algo extremo?',
      '¿Has tenido un “tren” o situación de varios?',
      '¿Cuál es la cosa más asquerosa (sexualmente) que has hecho?',
      '¿Has follado en el suelo, contra la pared o en lugares sucios de fiesta?',
      '¿Te has corrido en la cara o cuerpo de alguien en una fiesta?',
      '¿Has participado en juegos de poder o humillación en grupo?',
      '¿Quién de los presentes te gustaría que te usara como quisiera?',
      '¿Cuál es tu límite más bajo que has cruzado borracho/a?',
      '¿Te has dejado marcar o azotar en una fiesta?',
      '¿Has tenido un orgasmo solo de estimulación oral extrema en grupo?',
      '¿Quién de aquí tiene el fetiche más raro según tú?',
      '¿Has tenido sexo con alguien mientras su pareja estaba cerca?',
      '¿Cuál es la situación más riesgosa sexualmente que has vivido?',
      '¿Has usado comida, alcohol o líquidos de forma extrema?',
      '¿Te has quedado en una fiesta solo/a para follar con alguien?',
      '¿Has tenido un “yes day” sexual extremo en una noche?',
      '¿Quién de los presentes te gustaría que te degradara verbalmente?',
      '¿Has hecho un reto de “todo vale” en una fiesta?',
      '¿Cuál es la cosa más extrema que harías ahora mismo por dinero o un reto?',
      '¿Has tenido sexo en un coche con varias personas mirando o participando?',
      '¿Te has dejado follar mientras otros daban instrucciones?',
      '¿Has tenido un orgasmo colectivo o en cadena?',
      '¿Quién de aquí te parece más capaz de un trío extremo?',
      '¿Has cruzado límites de dolor o intensidad en una fiesta?',
      '¿Cuál es tu mayor arrepentimiento extremo de una noche de fiesta?',
      '¿Has hecho algo que después no podías creer que hiciste?',
      '¿Aceptarías un reto extremo total ahora mismo si el grupo lo decide?',
    ],
    'reto': [
      'Quítate toda la ropa y quédate desnudo/a 30 segundos.',
      'Elige a alguien y dale un oral de 20 segundos (o simúlalo de forma extrema).',
      'Deja que el grupo te dé 5 azotes (suaves o fuertes).',
      'Di en voz alta a quién te follarías ahora y cómo.',
      'Elige a dos personas y haz que te toquen a la vez 20 segundos.',
      'Quítate la ropa interior y enséñala al grupo.',
      'Deja que te escriban frases sucias por el cuerpo.',
      'Haz un striptease completo de 40 segundos.',
      'Di las palabras más degradantes que aceptas que te digan.',
      'Ponte a cuatro patas y deja que te usen 20 segundos.',
      'Deja que alguien te controle el orgasmo (no te corras hasta que digan).',
      'Elige a alguien y chúpale o lámelo de forma extrema.',
      'Quítate todo y camina desnudo/a por la habitación.',
      'Deja que el grupo vote qué te hacen ahora.',
      'Deja que te marquen el cuerpo con chupetones o azotes.',
      'Di “úsenme como quieran” y cumple 30 segundos.',
      'Elige a tres personas y da un beso extremo a cada una.',
      'Ponte en posición de sumisión total y no te muevas.',
      'Haz el sonido y cara de corrida más extrema.',
      'Elige a alguien y deja que te folle verbalmente en detalle.',
      'Quítate la ropa y siéntate en el regazo de alguien desnudo/a.',
      'Deja que te toquen entre varios a la vez 20 segundos.',
      'Di tu fantasía más extrema y pide que la cumplan un poco.',
      'Ponte de rodillas y abre la boca para el grupo.',
      'Deja que te azoten mientras dices lo que sientes.',
      'Elige a alguien y deja que te use contra la pared.',
      'Haz un 69 improvisado (o posición extrema) 20 segundos.',
      'Deja que te escriban “puta/puto de la fiesta” o similar.',
      'Quítate todo y deja que te miren y comenten 30 segundos.',
      'Elige a alguien y pide que te degrade en voz alta.',
      'Deja que te controlen completamente 40 segundos.',
      'Haz un movimiento de follar extremo en el aire o con alguien.',
      'Di a quién dejarías que te follara sin límites esta noche.',
      'Deja que te usen la boca y las manos a la vez.',
      'Ponte en la posición más vulnerable y mantente.',
      'Elige a dos personas y deja que te den órdenes sexuales.',
      'Quítate la ropa y haz un baile completamente desnudo/a.',
      'Deja que te marquen o escriban en zonas íntimas.',
      'Di “fóllenme” de forma realista y repetida.',
      'Deja que el grupo decida tu próximo acto extremo.',
      'Haz un oral o estimulación extrema a quien elijan.',
      'Ponte completamente a disposición del grupo 1 minuto.',
      'Deja que te usen hasta que digan basta.',
      'Di la cosa más extrema que estás dispuesto/a a hacer ahora.',
      'Termina pidiendo que el grupo te use de la forma más extrema que se les ocurra (con consentimiento claro de todos).',
    ],
  },
};
