const extraWordBank = <String, Map<String, String>>{
  'Profesiones': {
    'Médico': 'Profesión · consulta',
    'Enfermero': 'Profesión · cuidados',
    'Bombero': 'Profesión · emergencia',
    'Policía': 'Profesión · patrulla',
    'Profesor': 'Profesión · enseñanza',
    'Arquitecto': 'Profesión · planos',
    'Abogado': 'Profesión · defensa',
    'Juez': 'Profesión · veredicto',
    'Cocinero': 'Profesión · fogones',
    'Camarero': 'Profesión · bandeja',
    'Piloto': 'Profesión · cabina',
    'Azafata': 'Profesión · pasajeros',
    'Veterinario': 'Profesión · mascotas',
    'Dentista': 'Profesión · muelas',
    'Farmacéutico': 'Profesión · medicamentos',
    'Periodista': 'Profesión · noticias',
    'Fotógrafo': 'Profesión · retratos',
    'Pintor': 'Profesión · lienzo',
    'Actor': 'Profesión · escenario',
    'Cantante': 'Profesión · micrófono',
    'Músico': 'Profesión · melodía',
    'Bailarín': 'Profesión · coreografía',
    'Escritor': 'Profesión · novela',
    'Bibliotecario': 'Profesión · préstamos',
    'Científico': 'Profesión · investigación',
    'Astronauta': 'Profesión · órbita',
    'Ingeniero': 'Profesión · proyectos',
    'Programador': 'Profesión · código',
    'Diseñador': 'Profesión · creatividad',
    'Electricista': 'Profesión · cables',
    'Fontanero': 'Profesión · tuberías',
    'Carpintero': 'Profesión · madera',
    'Mecánico': 'Profesión · motores',
    'Albañil': 'Profesión · ladrillos',
    'Jardinero': 'Profesión · plantas',
    'Agricultor': 'Profesión · cosecha',
    'Pescador': 'Profesión · redes',
    'Taxista': 'Profesión · trayecto',
    'Repartidor': 'Profesión · paquetes',
    'Peluquero': 'Profesión · peinado',
    'Sastre': 'Profesión · medidas',
    'Zapatero': 'Profesión · suelas',
    'Joyero': 'Profesión · gemas',
    'Socorrista': 'Profesión · rescate',
    'Entrenador': 'Profesión · equipo',
    'Árbitro': 'Profesión · silbato',
    'Detective': 'Profesión · pistas',
    'Traductor': 'Profesión · idiomas',
    'Psicólogo': 'Profesión · terapia',
    'Arqueólogo': 'Profesión · excavación',
  },
  'Deportes': {
    'Fútbol': 'Deporte · portería',
    'Baloncesto': 'Deporte · canasta',
    'Tenis': 'Deporte · saque',
    'Pádel': 'Deporte · paredes',
    'Voleibol': 'Deporte · remate',
    'Balonmano': 'Deporte · siete metros',
    'Béisbol': 'Deporte · bate',
    'Rugby': 'Deporte · melé',
    'Hockey': 'Deporte · disco',
    'Golf': 'Deporte · hoyo',
    'Natación': 'Deporte · largos',
    'Waterpolo': 'Deporte · piscina',
    'Atletismo': 'Deporte · pista ovalada',
    'Maratón': 'Deporte · resistencia',
    'Ciclismo': 'Deporte · pelotón',
    'Boxeo': 'Deporte · guantes',
    'Judo': 'Deporte · tatami',
    'Karate': 'Deporte · cinturón',
    'Taekwondo': 'Deporte · patadas',
    'Esgrima': 'Deporte · florete',
    'Gimnasia artística': 'Deporte · piruetas',
    'Halterofilia': 'Deporte · levantamiento',
    'Escalada': 'Deporte · agarres',
    'Surf': 'Deporte · olas',
    'Windsurf': 'Deporte · vela acuática',
    'Piragüismo': 'Deporte · pala',
    'Remo': 'Deporte · regata',
    'Navegación a vela': 'Deporte · viento marino',
    'Esquí': 'Deporte · nieve',
    'Snowboard': 'Deporte · tabla nevada',
    'Patinaje artístico': 'Deporte · hielo musical',
    'Patinaje de velocidad': 'Deporte · vueltas rápidas',
    'Bádminton': 'Deporte · volante',
    'Tenis de mesa': 'Deporte · paleta pequeña',
    'Squash': 'Deporte · frontón cerrado',
    'Tiro con arco': 'Deporte · diana',
    'Equitación': 'Deporte · montura',
    'Polo': 'Deporte · caballo y mazo',
    'Triatlón': 'Deporte · tres disciplinas',
    'Pentatlón': 'Deporte · cinco pruebas',
    'Motociclismo': 'Deporte · circuito a dos ruedas',
    'Automovilismo': 'Deporte · bandera a cuadros',
    'Skateboard': 'Deporte · trucos urbanos',
    'Parkour': 'Deporte · obstáculos',
    'Bolos': 'Deporte · pleno',
    'Billar': 'Deporte · taco',
    'Dardos': 'Deporte · triple veinte',
    'Ajedrez': 'Deporte · jaque',
    'Lucha libre': 'Deporte · agarre',
    'Críquet': 'Deporte · wickets',
  },
  'Transportes': {
    'Coche': 'Transporte · cuatro puertas',
    'Autobús': 'Transporte · línea urbana',
    'Tren': 'Transporte · raíles',
    'Avión': 'Transporte · alas',
    'Barco': 'Transporte · cubierta',
    'Metro': 'Transporte · subterráneo',
    'Tranvía': 'Transporte · vía urbana',
    'Taxi': 'Transporte · taxímetro',
    'Motocicleta': 'Transporte · casco obligatorio',
    'Camión': 'Transporte · remolque',
    'Furgoneta': 'Transporte · carga compacta',
    'Helicóptero': 'Transporte · rotor',
    'Submarino': 'Transporte · profundidad',
    'Velero': 'Transporte · mástil',
    'Yate': 'Transporte · lujo náutico',
    'Canoa': 'Transporte · pala simple',
    'Kayak': 'Transporte · pala doble',
    'Ferry': 'Transporte · cruce marítimo',
    'Crucero': 'Transporte · vacaciones flotantes',
    'Ambulancia': 'Transporte · sirena médica',
    'Camión de bomberos': 'Transporte · escalera roja',
    'Tractor': 'Transporte · campo',
    'Excavadora': 'Transporte · pala mecánica',
    'Grúa': 'Transporte · gancho',
    'Caravana': 'Transporte · casa rodante',
    'Autocaravana': 'Transporte · viaje con cama',
    'Monopatín': 'Transporte · tabla con ruedas',
    'Segway': 'Transporte · equilibrio eléctrico',
    'Teleférico': 'Transporte · cable aéreo',
    'Funicular': 'Transporte · pendiente',
    'Globo aerostático': 'Transporte · aire caliente',
    'Dirigible': 'Transporte · gran globo',
    'Cohete': 'Transporte · despegue espacial',
    'Nave espacial': 'Transporte · cosmos',
    'Trineo': 'Transporte · nieve tirada',
    'Moto de agua': 'Transporte · velocidad marina',
    'Catamarán': 'Transporte · dos cascos',
    'Góndola': 'Transporte · canales venecianos',
    'Limusina': 'Transporte · vehículo alargado',
    'Todoterreno': 'Transporte · camino difícil',
    'Descapotable': 'Transporte · techo abierto',
    'Coche de carreras': 'Transporte · monoplaza',
    'Camión cisterna': 'Transporte · depósito',
    'Hormigonera': 'Transporte · tambor giratorio',
    'Apisonadora': 'Transporte · rodillo pesado',
    'Carretilla elevadora': 'Transporte · palés',
    'Remolcador': 'Transporte · arrastre portuario',
    'Hidroavión': 'Transporte · aterrizaje acuático',
    'Parapente': 'Transporte · vuelo sin motor',
    'Tuk-tuk': 'Transporte · tres ruedas',
  },
  'Instrumentos': {
    'Guitarra': 'Instrumento · seis cuerdas',
    'Piano': 'Instrumento · teclas blancas',
    'Violín': 'Instrumento · arco pequeño',
    'Batería musical': 'Instrumento · baquetas',
    'Flauta': 'Instrumento · soplo ligero',
    'Trompeta': 'Instrumento · metal brillante',
    'Saxofón': 'Instrumento · jazz',
    'Clarinete': 'Instrumento · caña simple',
    'Trombón': 'Instrumento · vara',
    'Tuba': 'Instrumento · grave metálico',
    'Violonchelo': 'Instrumento · arco sentado',
    'Contrabajo': 'Instrumento · cuerda gigante',
    'Arpa': 'Instrumento · cuerdas verticales',
    'Ukelele': 'Instrumento · cuatro cuerdas',
    'Banjo': 'Instrumento · cuerpo circular',
    'Mandolina': 'Instrumento · cuerda italiana',
    'Acordeón': 'Instrumento · fuelle',
    'Armónica': 'Instrumento · bolsillo musical',
    'Oboe': 'Instrumento · doble lengüeta',
    'Fagot': 'Instrumento · tubo de madera',
    'Piccolo': 'Instrumento · flauta aguda',
    'Corneta': 'Instrumento · llamada militar',
    'Timbal': 'Instrumento · parche afinado',
    'Xilófono': 'Instrumento · láminas de madera',
    'Marimba': 'Instrumento · resonadores',
    'Vibráfono': 'Instrumento · placas metálicas',
    'Pandereta': 'Instrumento · sonajas',
    'Castañuelas': 'Instrumento · palmas flamencas',
    'Maracas': 'Instrumento · semillas',
    'Bongós': 'Instrumento · pareja de tambores',
    'Congas': 'Instrumento · percusión cubana',
    'Cajón flamenco': 'Instrumento · asiento rítmico',
    'Triángulo musical': 'Instrumento · varilla metálica',
    'Platillos': 'Instrumento · choque circular',
    'Gong': 'Instrumento · disco oriental',
    'Campanas tubulares': 'Instrumento · tubos colgantes',
    'Órgano': 'Instrumento · tubos y pedales',
    'Sintetizador': 'Instrumento · sonido electrónico',
    'Teclado musical': 'Instrumento · piano portátil',
    'Sampler': 'Instrumento · fragmentos sonoros',
    'Gaita': 'Instrumento · bolsa de aire',
    'Dulzaina': 'Instrumento · fiesta tradicional',
    'Ocarina': 'Instrumento · vasija sonora',
    'Laúd': 'Instrumento · mástil antiguo',
    'Sitar': 'Instrumento · cuerdas indias',
    'Balalaica': 'Instrumento · cuerpo triangular',
    'Didyeridú': 'Instrumento · tubo australiano',
    'Kalimba': 'Instrumento · láminas con pulgares',
    'Theremín': 'Instrumento · sin tocar',
    'Kazoo': 'Instrumento · zumbido',
  },
  'Personajes': {
    'Sherlock Holmes': 'Personaje · detective londinense',
    'Cenicienta': 'Personaje · zapato perdido',
    'Pinocho': 'Personaje · nariz sincera',
    'Peter Pan': 'Personaje · nunca crece',
    'Caperucita Roja': 'Personaje · camino del bosque',
    'Blancanieves': 'Personaje · siete compañeros',
    'Aladino': 'Personaje · lámpara mágica',
    'Robin Hood': 'Personaje · arquero generoso',
    'Drácula': 'Personaje · conde nocturno',
    'Frankenstein': 'Personaje · criatura cosida',
    'Don Quijote': 'Personaje · molinos',
    'Sancho Panza': 'Personaje · escudero fiel',
    'Romeo': 'Personaje · enamorado de Verona',
    'Julieta': 'Personaje · balcón romántico',
    'Hamlet': 'Personaje · príncipe dudoso',
    'Hércules': 'Personaje · doce trabajos',
    'Ulises': 'Personaje · viaje a Ítaca',
    'Aquiles': 'Personaje · talón vulnerable',
    'Zeus': 'Personaje · rayo olímpico',
    'Poseidón': 'Personaje · tridente marino',
    'Medusa mitológica': 'Personaje · mirada de piedra',
    'Merlín': 'Personaje · mago legendario',
    'Rey Arturo': 'Personaje · espada en piedra',
    'Lancelot': 'Personaje · caballero redondo',
    'Tarzán': 'Personaje · selva humana',
    'Mowgli': 'Personaje · niño entre lobos',
    'Alicia': 'Personaje · país maravilloso',
    'Sombrerero Loco': 'Personaje · merienda eterna',
    'Principito': 'Personaje · pequeño planeta',
    'Papá Noel': 'Personaje · regalos de diciembre',
    'Ratón Pérez': 'Personaje · dientes bajo almohada',
    'Ratoncito de los dientes': 'Personaje · moneda nocturna',
    'Quasimodo': 'Personaje · campanero parisino',
    'D’Artagnan': 'Personaje · cuarto mosquetero',
    'Zorro enmascarado': 'Personaje · firma con espada',
    'Capitán Garfio': 'Personaje · mano metálica',
    'Simbad': 'Personaje · marinero aventurero',
    'Mago de Oz': 'Personaje · ciudad esmeralda',
    'Dorothy': 'Personaje · zapatos y tornado',
    'Espantapájaros de Oz': 'Personaje · busca cerebro',
    'Hombre de Hojalata': 'Personaje · busca corazón',
    'León Cobarde': 'Personaje · busca valor',
    'Gato con Botas': 'Personaje · felino espadachín',
    'Bella Durmiente': 'Personaje · sueño encantado',
    'Rapunzel': 'Personaje · cabello de torre',
    'Hansel': 'Personaje · casa de dulces',
    'Gretel': 'Personaje · horno de bruja',
    'Sirenita': 'Personaje · voz submarina',
    'Patito Feo': 'Personaje · transformación blanca',
    'Flautista de Hamelín': 'Personaje · música y ratones',
  },
  'Acciones': {
    'Correr': 'Acción · ir deprisa',
    'Saltar': 'Acción · despegar del suelo',
    'Bailar': 'Acción · seguir el ritmo',
    'Cantar': 'Acción · usar la voz',
    'Dormir': 'Acción · cerrar los ojos',
    'Soñar': 'Acción · imaginar dormido',
    'Reír': 'Acción · mostrar alegría',
    'Llorar': 'Acción · soltar lágrimas',
    'Estornudar': 'Acción · reflejo nasal',
    'Bostezar': 'Acción · abrir mucho la boca',
    'Aplaudir': 'Acción · juntar las manos',
    'Silbar': 'Acción · sonido con labios',
    'Susurrar': 'Acción · hablar bajito',
    'Gritar': 'Acción · subir la voz',
    'Leer': 'Acción · seguir letras',
    'Escribir': 'Acción · formar palabras',
    'Dibujar': 'Acción · crear líneas',
    'Pintar': 'Acción · aplicar color',
    'Cocinar': 'Acción · preparar alimentos',
    'Comer': 'Acción · llevar a la boca',
    'Beber': 'Acción · tomar líquido',
    'Masticar': 'Acción · usar los dientes',
    'Oler': 'Acción · usar la nariz',
    'Escuchar': 'Acción · prestar oído',
    'Mirar': 'Acción · dirigir la vista',
    'Tocar': 'Acción · sentir con la piel',
    'Abrazar': 'Acción · rodear con brazos',
    'Besar': 'Acción · acercar los labios',
    'Saludar': 'Acción · reconocer a alguien',
    'Despedirse': 'Acción · decir adiós',
    'Caminar': 'Acción · avanzar a pie',
    'Nadar': 'Acción · moverse en agua',
    'Bucear': 'Acción · bajar bajo el agua',
    'Volar': 'Acción · desplazarse por aire',
    'Conducir': 'Acción · manejar vehículo',
    'Pedalear': 'Acción · mover con piernas',
    'Trepar': 'Acción · subir agarrándose',
    'Lanzar': 'Acción · enviar con fuerza',
    'Atrapar': 'Acción · coger en movimiento',
    'Empujar': 'Acción · alejar con fuerza',
    'Tirar': 'Acción · atraer hacia uno',
    'Abrir': 'Acción · dejar acceso',
    'Cerrar': 'Acción · impedir el paso',
    'Encender': 'Acción · poner en marcha',
    'Apagar': 'Acción · detener energía',
    'Construir': 'Acción · crear por piezas',
    'Romper': 'Acción · separar dañando',
    'Limpiar': 'Acción · quitar suciedad',
    'Ordenar': 'Acción · poner en su sitio',
    'Esconder': 'Acción · evitar que se vea',
  },
};
