import 'word_data_extra.dart';
import 'word_data_concrete.dart';
import 'word_data_global_figures.dart';

/// Banco base de palabras del juego. Cada entrada relaciona una palabra secreta
/// con una pista breve y deliberadamente indirecta para el impostor.
const baseWordBank = <String, Map<String, String>>{
  'Lugares': {
    'Aeropuerto': 'Embarque',
    'Biblioteca': 'Estanterías',
    'Camping': 'Tienda',
    'Museo': 'Exposición',
    'Playa': 'Orilla',
    'Restaurante': 'Reserva',
    'Gimnasio': 'Pesas',
    'Hospital': 'Urgencias',
    'Cine': 'Palomitas',
    'Supermercado': 'Carrito',
    'Estación de tren': 'Andén',
    'Colegio': 'Recreo',
    'Universidad': 'Campus',
    'Parque': 'Columpio',
    'Zoológico': 'Recintos',
    'Acuario': 'Pecera',
    'Estadio': 'Gradas',
    'Teatro': 'Telón',
    'Hotel': 'Recepción',
    'Farmacia': 'Receta',
    'Panadería': 'Horno',
    'Peluquería': 'Tijeras',
    'Comisaría': 'Denuncia',
    'Gasolinera': 'Surtidor',
    'Iglesia': 'Campana',
    'Castillo': 'Muralla',
    'Faro': 'Costa',
    'Puerto': 'Muelle',
    'Montaña': 'Cumbre',
    'Bosque': 'Sendero',
    'Desierto': 'Dunas',
    'Isla': 'Archipiélago',
    'Cueva': 'Estalactita',
    'Cascada': 'Caudal',
    'Piscina': 'Cloro',
    'Discoteca': 'Pista',
    'Banco': 'Ventanilla',
    'Oficina': 'Reunión',
    'Fábrica': 'Producción',
    'Laboratorio': 'Probeta',
    'Cementerio': 'Lápida',
    'Circo': 'Carpa',
    'Mercado': 'Puestos',
    'Ayuntamiento': 'Alcaldía',
    'Juzgado': 'Sentencia',
    'Spa': 'Relax',
    'Lavandería': 'Centrifugado',
    'Taller mecánico': 'Elevador',
    'Floristería': 'Ramo',
    'Observatorio': 'Telescopio',
  },
  'Comida': {
    'Croissant': 'Hojaldre',
    'Paella': 'Azafrán',
    'Sushi': 'Nori',
    'Tacos': 'Tortilla',
    'Pizza': 'Mozzarella',
    'Helado': 'Cucurucho',
    'Lasaña': 'Bechamel',
    'Hamburguesa': 'Parrilla',
    'Tortilla de patatas': 'Cuajada',
    'Gazpacho': 'Verano',
    'Churros': 'Chocolate',
    'Empanada': 'Relleno',
    'Ceviche': 'Lima',
    'Ramen': 'Caldo',
    'Cuscús': 'Sémola',
    'Falafel': 'Garbanzos',
    'Burrito': 'Enrollado',
    'Nachos': 'Crujiente',
    'Hot dog': 'Mostaza',
    'Ensalada César': 'Picatostes',
    'Risotto': 'Cremoso',
    'Ñoquis': 'Patata',
    'Raviolis': 'Paquetitos',
    'Kebab': 'Asador',
    'Pollo asado': 'Brocheta',
    'Albóndigas': 'Redondas',
    'Croquetas': 'Rebozado',
    'Fabada': 'Asturias',
    'Pulpo a la gallega': 'Pimentón',
    'Jamón serrano': 'Curación',
    'Queso manchego': 'Cuña',
    'Salmorejo': 'Córdoba',
    'Migas': 'Pan',
    'Tiramisú': 'Café',
    'Flan': 'Caramelo',
    'Tarta de queso': 'Molde',
    'Brownie': 'Cacao',
    'Donut': 'Aro',
    'Macarons': 'Almendra',
    'Crepes': 'Sartén',
    'Gofres': 'Rejilla',
    'Yogur': 'Fermento',
    'Batido': 'Pajita',
    'Palomitas': 'Maíz',
    'Aceitunas': 'Hueso',
    'Guacamole': 'Aguacate',
    'Hummus': 'Tahini',
    'Sopa de fideos': 'Cuchara',
    'Puré de verduras': 'Triturado',
    'Sandwich': 'Dos rebanadas',
  },
  'Objetos': {
    'Paraguas': 'Chaparrón',
    'Brújula': 'Orientación',
    'Martillo': 'Clavo',
    'Espejo': 'Imagen',
    'Mochila': 'Correas',
    'Reloj': 'Minutos',
    'Cámara': 'Objetivo',
    'Teléfono': 'Llamada',
    'Ordenador': 'Teclado',
    'Auriculares': 'Oídos',
    'Gafas': 'Cristales',
    'Llaves': 'Cerradura',
    'Cartera': 'Bolsillo',
    'Linterna': 'Oscuridad',
    'Vela': 'Mecha',
    'Tijeras': 'Cortar',
    'Pegamento': 'Adhesivo',
    'Destornillador': 'Tornillo',
    'Taladro': 'Broca',
    'Escoba': 'Barrer',
    'Aspiradora': 'Polvo',
    'Plancha': 'Arrugas',
    'Lavadora': 'Tambor',
    'Nevera': 'Refrigerar',
    'Microondas': 'Calentar',
    'Tostadora': 'Ranuras',
    'Batidora': 'Cuchillas',
    'Cafetera': 'Filtro',
    'Sartén': 'Freír',
    'Cuchillo': 'Filo',
    'Tenedor': 'Púas',
    'Cuchara': 'Sopa',
    'Botella': 'Tapón',
    'Termo': 'Temperatura',
    'Maleta': 'Equipaje',
    'Casco': 'Protección',
    'Bicicleta': 'Pedales',
    'Patinete': 'Manillar',
    'Balón': 'Partido',
    'Raqueta': 'Red',
    'Dado': 'Caras',
    'Baraja': 'Naipes',
    'Pincel': 'Cerdas',
    'Lápiz': 'Grafito',
    'Cuaderno': 'Páginas',
    'Grapadora': 'Grapas',
    'Calculadora': 'Cuentas',
    'Mando a distancia': 'Canales',
    'Cargador': 'Batería',
    'Altavoz': 'Volumen',
  },
  'Animales': {
    'Pingüino': 'Antártida',
    'Delfín': 'Sonar',
    'Jirafa': 'Cuello',
    'Camaleón': 'Camuflaje',
    'Koala': 'Eucalipto',
    'Pulpo': 'Ocho brazos',
    'Flamenco': 'Laguna',
    'Elefante': 'Trompa',
    'León': 'Melena',
    'Tigre': 'Rayas',
    'Cebra': 'Blanco y negro',
    'Rinoceronte': 'Cuerno',
    'Hipopótamo': 'Río',
    'Cocodrilo': 'Mandíbula',
    'Serpiente': 'Escamas',
    'Tortuga': 'Caparazón',
    'Canguro': 'Bolsa',
    'Panda': 'Bambú',
    'Oso polar': 'Ártico',
    'Lobo': 'Manada',
    'Zorro': 'Madriguera',
    'Ciervo': 'Astas',
    'Ardilla': 'Bellota',
    'Erizo': 'Púas defensivas',
    'Conejo': 'Orejas',
    'Murciélago': 'Ecolocalización',
    'Búho': 'Nocturno',
    'Águila': 'Vuelo',
    'Loro': 'Imitación',
    'Pavo real': 'Abanico',
    'Avestruz': 'Carrera',
    'Gallina': 'Gallinero',
    'Caballo': 'Galope',
    'Vaca': 'Pradera',
    'Oveja': 'Lana',
    'Cabra': 'Pezuñas',
    'Cerdo': 'Hocico',
    'Perro': 'Ladrido',
    'Gato': 'Bigotes',
    'Hámster': 'Rueda',
    'Rana': 'Charca',
    'Salamandra': 'Anfibio',
    'Tiburón': 'Aleta',
    'Ballena': 'Espiráculo',
    'Medusa': 'Gelatina',
    'Caballito de mar': 'Coral',
    'Cangrejo': 'Pinzas',
    'Mariposa': 'Metamorfosis',
    'Abeja': 'Colmena',
    'Hormiga': 'Hormiguero',
  },
};

final wordBank = <String, Map<String, String>>{
  ...baseWordBank,
  ...extraWordBank,
  ...concreteWordBank,
  ...globalFiguresWordBank,
};
