/// Figuras con reconocimiento internacional amplio.
const globalFiguresWordBank = <String, Map<String, String>>{
  'Actores': {
    'Tom Hanks': 'Actor mundial · náufrago',
    'Leonardo DiCaprio': 'Actor mundial · iceberg',
    'Brad Pitt': 'Actor mundial · club secreto',
    'Angelina Jolie': 'Actor mundial · arqueóloga aventurera',
    'Johnny Depp': 'Actor mundial · pirata excéntrico',
    'Will Smith': 'Actor mundial · hombres de negro',
    'Denzel Washington': 'Actor mundial · día de entrenamiento',
    'Morgan Freeman': 'Actor mundial · voz profunda',
    'Robert Downey Jr.': 'Actor mundial · armadura tecnológica',
    'Scarlett Johansson': 'Actor mundial · espía pelirroja',
    'Chris Hemsworth': 'Actor mundial · martillo divino',
    'Chris Evans': 'Actor mundial · escudo con estrella',
    'Tom Cruise': 'Actor mundial · misión imposible',
    'Keanu Reeves': 'Actor mundial · elegido digital',
    'Jackie Chan': 'Actor mundial · acrobacias marciales',
    'Arnold Schwarzenegger': 'Actor mundial · robot del futuro',
    'Sylvester Stallone': 'Actor mundial · boxeador de Filadelfia',
    'Dwayne Johnson': 'Actor mundial · la roca',
    'Meryl Streep': 'Actor mundial · editora exigente',
    'Julia Roberts': 'Actor mundial · sonrisa inolvidable',
    'Sandra Bullock': 'Actor mundial · velocidad en autobús',
    'Jennifer Aniston': 'Actor mundial · amiga de Nueva York',
    'Nicole Kidman': 'Actor mundial · cabaret parisino',
    'Natalie Portman': 'Actor mundial · cisne oscuro',
    'Emma Watson': 'Actor mundial · joven bruja estudiosa',
    'Daniel Radcliffe': 'Actor mundial · cicatriz y gafas',
    'Hugh Jackman': 'Actor mundial · garras metálicas',
    'Ryan Reynolds': 'Actor mundial · antihéroe rojo',
    'Ryan Gosling': 'Actor mundial · conductor nocturno',
    'Margot Robbie': 'Actor mundial · muñeca rosa',
    'Anne Hathaway': 'Actor mundial · princesa inesperada',
    'Jennifer Lawrence': 'Actor mundial · arquera rebelde',
    'Emma Stone': 'Actor mundial · ciudad de estrellas',
    'Zendaya': 'Actor mundial · adolescente y arena',
    'Pedro Pascal': 'Actor mundial · protector viajero',
    'Antonio Banderas': 'Actor mundial · espadachín enmascarado',
    'Penélope Cruz': 'Actor mundial · premio español',
    'Javier Bardem': 'Actor mundial · villano de película',
    'Samuel L. Jackson': 'Actor mundial · parche en el ojo',
    'George Clooney': 'Actor mundial · ladrón elegante',
    'Matt Damon': 'Actor mundial · agente sin memoria',
    'Ben Affleck': 'Actor mundial · murciélago de Gotham',
    'Liam Neeson': 'Actor mundial · búsqueda implacable',
    'Harrison Ford': 'Actor mundial · arqueólogo con látigo',
    'Mark Hamill': 'Actor mundial · caballero galáctico',
    'Sigourney Weaver': 'Actor mundial · superviviente espacial',
    'Michelle Yeoh': 'Actor mundial · universos paralelos',
    'Cate Blanchett': 'Actor mundial · reina élfica',
    'Joaquin Phoenix': 'Actor mundial · risa inquietante',
    'Al Pacino': 'Actor mundial · padrino siciliano',
  },
  'Cantantes': {
    'Michael Jackson': 'Cantante mundial · paso lunar',
    'Madonna': 'Cantante mundial · reina del pop',
    'Beyoncé': 'Cantante mundial · reina B',
    'Taylor Swift': 'Cantante mundial · eras musicales',
    'Rihanna': 'Cantante mundial · paraguas caribeño',
    'Lady Gaga': 'Cantante mundial · vestuario extravagante',
    'Adele': 'Cantante mundial · voz británica',
    'Shakira': 'Cantante mundial · caderas colombianas',
    'Ed Sheeran': 'Cantante mundial · guitarra pelirroja',
    'Justin Bieber': 'Cantante mundial · ídolo canadiense',
    'Ariana Grande': 'Cantante mundial · coleta alta',
    'Bruno Mars': 'Cantante mundial · funk hawaiano',
    'The Weeknd': 'Cantante mundial · luces cegadoras',
    'Billie Eilish': 'Cantante mundial · susurro verde',
    'Dua Lipa': 'Cantante mundial · reglas nuevas',
    'Miley Cyrus': 'Cantante mundial · flores',
    'Katy Perry': 'Cantante mundial · fuegos artificiales',
    'Britney Spears': 'Cantante mundial · princesa del pop',
    'Whitney Houston': 'Cantante mundial · voz poderosa',
    'Mariah Carey': 'Cantante mundial · Navidad aguda',
    'Céline Dion': 'Cantante mundial · corazón de barco',
    'Elton John': 'Cantante mundial · gafas brillantes',
    'Freddie Mercury': 'Cantante mundial · reina del rock',
    'Stevie Wonder': 'Cantante mundial · piano y soul',
    'Paul McCartney': 'Cantante mundial · bajo de Liverpool',
    'Mick Jagger': 'Cantante mundial · lengua del rock',
    'Bruce Springsteen': 'Cantante mundial · jefe americano',
    'Eminem': 'Cantante mundial · rapero de Detroit',
    'Drake': 'Cantante mundial · rap canadiense',
    'Snoop Dogg': 'Cantante mundial · rap relajado',
    'Jennifer Lopez': 'Cantante mundial · Bronx y baile',
    'Christina Aguilera': 'Cantante mundial · voz y genio',
    'Selena Gomez': 'Cantante mundial · amor como canción',
    'Harry Styles': 'Cantante mundial · sandía dulce',
    'Justin Timberlake': 'Cantante mundial · traje y corbata',
    'Alicia Keys': 'Cantante mundial · piano neoyorquino',
    'Usher': 'Cantante mundial · R&B y baile',
    'Pink': 'Cantante mundial · acrobacia aérea',
    'Sia': 'Cantante mundial · rostro oculto',
    'Kylie Minogue': 'Cantante mundial · pop australiano',
    'Enrique Iglesias': 'Cantante mundial · héroe latino',
    'Ricky Martin': 'Cantante mundial · vida loca',
    'Bad Bunny': 'Cantante mundial · conejo puertorriqueño',
    'Karol G': 'Cantante mundial · bichota',
    'Jungkook': 'Cantante mundial · estrella coreana',
    'Andrea Bocelli': 'Cantante mundial · tenor italiano',
    'Bob Marley': 'Cantante mundial · reggae jamaicano',
    'Elvis Presley': 'Cantante mundial · rey del rock',
    'Tina Turner': 'Cantante mundial · energía del rock',
    'Cher': 'Cantante mundial · voz grave eterna',
  },
};
