const concreteWordBank = <String, Map<String, String>>{
  'Actores': {
    'Antonio Banderas': 'Actor · Málaga',
    'Penélope Cruz': 'Actor · premio español',
    'Javier Bardem': 'Actor · villano de película',
    'Ricardo Darín': 'Actor · cine argentino',
    'Guillermo Francella': 'Actor · comedia porteña',
    'Cecilia Roth': 'Actor · musa de Almodóvar',
    'Gael García Bernal': 'Actor · México y motocicletas',
    'Diego Luna': 'Actor · rebelión galáctica',
    'Salma Hayek': 'Actor · Frida',
    'Eugenio Derbez': 'Actor · humor mexicano',
    'Pedro Pascal': 'Actor · protector viajero',
    'Sofía Vergara': 'Actor · familia moderna',
    'Ana de Armas': 'Actor · Cuba y Hollywood',
    'Andy García': 'Actor · padrino cubano',
    'Benicio del Toro': 'Actor · Puerto Rico',
    'Oscar Isaac': 'Actor · piloto rebelde',
    'Rita Moreno': 'Actor · leyenda latina',
    'Edward James Olmos': 'Actor · comandante espacial',
    'America Ferrera': 'Actor · moda y oficina',
    'Zoe Saldaña': 'Actor · mundos azules',
    'Tom Hanks': 'Actor · náufrago',
    'Meryl Streep': 'Actor · editora exigente',
    'Leonardo DiCaprio': 'Actor · iceberg',
    'Kate Winslet': 'Actor · retrato en barco',
    'Denzel Washington': 'Actor · día de entrenamiento',
    'Viola Davis': 'Actor · abogada brillante',
    'Brad Pitt': 'Actor · club secreto',
    'Angelina Jolie': 'Actor · arqueóloga aventurera',
    'George Clooney': 'Actor · ladrón elegante',
    'Julia Roberts': 'Actor · sonrisa inolvidable',
    'Keanu Reeves': 'Actor · elegido digital',
    'Sandra Bullock': 'Actor · velocidad en autobús',
    'Will Smith': 'Actor · hombres de negro',
    'Nicole Kidman': 'Actor · Australia',
    'Morgan Freeman': 'Actor · voz profunda',
    'Natalie Portman': 'Actor · cisne oscuro',
    'Joaquin Phoenix': 'Actor · risa inquietante',
    'Emma Stone': 'Actor · ciudad de estrellas',
    'Ryan Gosling': 'Actor · conductor nocturno',
    'Margot Robbie': 'Actor · muñeca rosa',
    'Robert Downey Jr.': 'Actor · armadura tecnológica',
    'Scarlett Johansson': 'Actor · espía pelirroja',
    'Chris Hemsworth': 'Actor · martillo divino',
    'Lupita Nyong’o': 'Actor · reina guerrera',
    'Samuel L. Jackson': 'Actor · parche en el ojo',
    'Anne Hathaway': 'Actor · princesa inesperada',
    'Daniel Craig': 'Actor · agente británico',
    'Cate Blanchett': 'Actor · reina élfica',
    'Hugh Jackman': 'Actor · garras metálicas',
    'Michelle Yeoh': 'Actor · universos paralelos',
  },
  'Cantantes': {
    'Shakira': 'Cantante · caderas colombianas',
    'Rosalía': 'Cantante · flamenco moderno',
    'Bad Bunny': 'Cantante · conejo puertorriqueño',
    'Karol G': 'Cantante · bichota',
    'Luis Miguel': 'Cantante · sol mexicano',
    'Juanes': 'Cantante · camisa negra',
    'Alejandro Sanz': 'Cantante · corazón partío',
    'Enrique Iglesias': 'Cantante · héroe latino',
    'Ricky Martin': 'Cantante · vida loca',
    'Gloria Estefan': 'Cantante · ritmo cubano',
    'Celia Cruz': 'Cantante · azúcar',
    'Juan Gabriel': 'Cantante · Divo de Juárez',
    'Vicente Fernández': 'Cantante · charro',
    'Selena Quintanilla': 'Cantante · reina del tex-mex',
    'Marc Anthony': 'Cantante · salsa neoyorquina',
    'Daddy Yankee': 'Cantante · gasolina',
    'J Balvin': 'Cantante · colores urbanos',
    'Maluma': 'Cantante · Medellín',
    'Sebastián Yatra': 'Cantante · tacones rojos',
    'Camilo': 'Cantante · bigote',
    'Aitana': 'Cantante · academia española',
    'Pablo Alborán': 'Cantante · malagueño romántico',
    'Lola Índigo': 'Cantante · espectáculo violeta',
    'David Bisbal': 'Cantante · rizos de Almería',
    'Raphael': 'Cantante · gran gesto escénico',
    'Julio Iglesias': 'Cantante · balada internacional',
    'Nathy Peluso': 'Cantante · fuerza argentina',
    'Tini Stoessel': 'Cantante · violeta argentina',
    'Duki': 'Cantante · trap de Buenos Aires',
    'Bizarrap': 'Cantante · sesiones con gorra',
    'Taylor Swift': 'Cantante · eras musicales',
    'Beyoncé': 'Cantante · reina B',
    'Adele': 'Cantante · voz británica',
    'Ed Sheeran': 'Cantante · guitarra pelirroja',
    'Bruno Mars': 'Cantante · funk hawaiano',
    'Lady Gaga': 'Cantante · vestuario extravagante',
    'Rihanna': 'Cantante · paraguas caribeño',
    'Billie Eilish': 'Cantante · susurro verde',
    'Dua Lipa': 'Cantante · reglas nuevas',
    'The Weeknd': 'Cantante · luces cegadoras',
    'Justin Bieber': 'Cantante · ídolo canadiense',
    'Ariana Grande': 'Cantante · coleta alta',
    'Miley Cyrus': 'Cantante · flores',
    'Harry Styles': 'Cantante · sandía dulce',
    'Elton John': 'Cantante · gafas brillantes',
    'Freddie Mercury': 'Cantante · reina del rock',
    'Michael Jackson': 'Cantante · paso lunar',
    'Madonna': 'Cantante · reina del pop',
    'Whitney Houston': 'Cantante · voz poderosa',
    'Stevie Wonder': 'Cantante · piano y soul',
  },
  'Escuela': {
    'Aula escolar': 'Escuela · clase',
    'Pizarra digital': 'Escuela · pantalla docente',
    'Pupitre': 'Escuela · mesa individual',
    'Recreo escolar': 'Escuela · descanso',
    'Examen': 'Escuela · evaluación',
    'Deberes': 'Escuela · tarea en casa',
    'Matrícula escolar': 'Escuela · inscripción',
    'Boletín de notas': 'Escuela · calificaciones',
    'Asignatura': 'Escuela · materia',
    'Tutoría': 'Escuela · orientación',
    'Excursión escolar': 'Escuela · salida educativa',
    'Comedor escolar': 'Escuela · almuerzo',
    'Patio del colegio': 'Escuela · juego exterior',
    'Taquilla escolar': 'Escuela · casillero',
    'Uniforme escolar': 'Escuela · ropa igual',
    'Estuche': 'Escuela · material guardado',
    'Sacapuntas': 'Escuela · punta fina',
    'Goma de borrar': 'Escuela · corregir lápiz',
    'Regla escolar': 'Escuela · medir líneas',
    'Compás escolar': 'Escuela · círculos',
    'Transportador de ángulos': 'Escuela · grados',
    'Rotulador fluorescente': 'Escuela · resaltar texto',
    'Carpeta de anillas': 'Escuela · hojas ordenadas',
    'Libro de texto': 'Escuela · lección impresa',
    'Agenda escolar': 'Escuela · fechas de tareas',
    'Cuaderno escolar': 'Escuela · apuntes',
    'Calculadora científica': 'Escuela · operaciones avanzadas',
    'Globo terráqueo': 'Escuela · mundo giratorio',
    'Mapa mural': 'Escuela · geografía colgada',
    'Tabla periódica': 'Escuela · elementos químicos',
    'Esqueleto didáctico': 'Escuela · anatomía',
    'Microscopio escolar': 'Escuela · seres diminutos',
    'Laboratorio escolar': 'Escuela · experimento de clase',
    'Gimnasio escolar': 'Escuela · educación física',
    'Biblioteca escolar': 'Escuela · lectura académica',
    'Director del colegio': 'Escuela · autoridad del centro',
    'Orientador escolar': 'Escuela · apoyo al alumno',
    'Delegado de clase': 'Escuela · representante',
    'Lista de asistencia': 'Escuela · presentes y ausentes',
    'Trabajo en grupo': 'Escuela · colaboración',
    'Presentación oral': 'Escuela · hablar ante la clase',
    'Proyecto de ciencias': 'Escuela · investigación juvenil',
    'Concurso de ortografía': 'Escuela · palabras correctas',
    'Festival escolar': 'Escuela · actuación de alumnos',
    'Graduación': 'Escuela · final de etapa',
    'Diploma académico': 'Escuela · reconocimiento',
    'Campana escolar': 'Escuela · cambio de clase',
    'Fila de alumnos': 'Escuela · orden de entrada',
    'Mochila escolar': 'Escuela · libros a la espalda',
    'Autobús escolar': 'Escuela · ruta de estudiantes',
  },
  'Infantiles': {
    'Unicornio mágico': 'Infantil · caballo con cuerno',
    'Dinosaurio amistoso': 'Infantil · gigante prehistórico',
    'Dragón de colores': 'Infantil · fuego fantástico',
    'Robot juguetón': 'Infantil · amigo metálico',
    'Pirata aventurero': 'Infantil · tesoro en el mar',
    'Princesa valiente': 'Infantil · corona heroica',
    'Castillo encantado': 'Infantil · palacio con magia',
    'Hada madrina': 'Infantil · varita y alas',
    'Duende travieso': 'Infantil · pequeño bromista',
    'Gigante bonachón': 'Infantil · enorme y amable',
    'Monstruo peludo': 'Infantil · criatura suave',
    'Fantasma simpático': 'Infantil · sábana amistosa',
    'Bruja divertida': 'Infantil · escoba y risas',
    'Mago aprendiz': 'Infantil · hechizos nuevos',
    'Superhéroe en capa': 'Infantil · salvar la ciudad',
    'Nave de juguete': 'Infantil · viaje espacial pequeño',
    'Planeta de caramelo': 'Infantil · mundo dulce',
    'Arcoíris brillante': 'Infantil · siete colores',
    'Nube sonriente': 'Infantil · cielo feliz',
    'Estrella fugaz': 'Infantil · deseo nocturno',
    'Luna de cuento': 'Infantil · noche ilustrada',
    'Sol con gafas': 'Infantil · verano animado',
    'Casa del árbol': 'Infantil · refugio entre ramas',
    'Cabaña de chocolate': 'Infantil · hogar comestible',
    'Bosque encantado': 'Infantil · árboles con magia',
    'Isla del tesoro': 'Infantil · mapa secreto',
    'Barco de papel': 'Infantil · navegación plegada',
    'Tren de juguete': 'Infantil · vagones pequeños',
    'Coche teledirigido': 'Infantil · mando y ruedas',
    'Avión de papel': 'Infantil · vuelo plegado',
    'Muñeca parlante': 'Infantil · juguete con voz',
    'Oso de peluche': 'Infantil · abrazo suave',
    'Caballito balancín': 'Infantil · montar sin avanzar',
    'Bloques de construcción': 'Infantil · torres de colores',
    'Plastilina': 'Infantil · moldear con manos',
    'Pompas de jabón': 'Infantil · burbujas flotantes',
    'Cometa voladora': 'Infantil · cuerda en el cielo',
    'Peonza giratoria': 'Infantil · vuelta sobre punta',
    'Canicas': 'Infantil · bolas de cristal',
    'Cromos': 'Infantil · colección intercambiable',
    'Disfraz de carnaval': 'Infantil · convertirse en otro',
    'Fiesta de cumpleaños': 'Infantil · velas y regalos',
    'Piñata': 'Infantil · sorpresa colgante',
    'Tobogán gigante': 'Infantil · bajar deslizándose',
    'Columpio volador': 'Infantil · balanceo alto',
    'Piscina de bolas': 'Infantil · baño de colores',
    'Teatro de marionetas': 'Infantil · muñecos con hilos',
    'Libro de pegatinas': 'Infantil · decorar páginas',
    'Cuento antes de dormir': 'Infantil · historia nocturna',
    'Canción de cuna': 'Infantil · melodía para dormir',
  },
};
